### PR TITLE
ST-411-Upgrade Case API Dependencies

### PR DESCRIPTION
**Pull request by geciciserkan**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/ST-411

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Review by osheaf01 — DISMISSED** [review]
LGTM

**Review by jaberelfasi — DISMISSED** [review]

**Review by osheaf01 — APPROVED** [review]
LGTM

**Review by osheaf01 — APPROVED** [review]
LGTM

**Review by ElifDenizEsea — APPROVED** [review]

**Review by pavihmcts — APPROVED** [review]

**Review by spotstory — COMMENTED** [review]
Is the change in version string format by design (v4.9.1 rather than 4.9.1)?
implementation group: 'com.github.hmcts', name: 'ccd-client', version: 'v4.9.1'

**Comment by geciciserkan** [comment]
> v4.9.1

yes it is correct usage, I had to change it as nfdiv team use that format as well

**Comment by geciciserkan** [comment]
LGTM

**Pull request merged**
